#!/usr/bin/env python3
"""
Real DanceTrack-val (11 official sequences, downloaded from the
Voxel51/DanceTrack Hugging Face mirror and converted to MOT format by
prep_dancetrack.py) failure-analysis experiment, replacing the fully
fabricated Figure A6 previously generated by
litepp/experiments/gen_a5a6.py (np.random-perturbed similarity matrices,
hand-picked DetA/AssA/HOTA numbers -- no DanceTrack data was used at all).

Three real measurements, mirroring the original figure's three panels:
  (a) ReID similarity: real genuine (same-identity) vs impostor
      (different-identity) cosine similarity, using the MOT17-trained MSFP
      fusion head applied zero-shot to real GT-box features on both MOT17
      and DanceTrack-val, to test whether appearance is actually
      discriminative on DanceTrack.
  (b) DetA/AssA comparison across four real tracker configurations
      (motion-only IoU, LITE single-layer, MSFP attention fusion,
      MSFP-Track with zero-shot ATL threshold), scored with the real,
      official TrackEval HOTA/DetA/AssA.
  (c) Real YOLOv8m detection-score distribution on DanceTrack vs the real
      MOT17 det.txt distribution, plus the real zero-shot ATL threshold
      prediction on DanceTrack vs MOT17's own oracle thresholds.
"""
import argparse
import json
import random
import shutil
import time
from pathlib import Path

import numpy as np
for _name, _builtin in [("float", float), ("int", int), ("bool", bool), ("object", object)]:
    if not hasattr(np, _name):
        setattr(np, _name, _builtin)
import torch

import sys
sys.path.insert(0, str(Path(__file__).resolve().parent))
from real_tracker import ByteTrackStyleTracker
from atl_paper_faithful import ATLPaperFaithful
from personpath22_zeroshot_eval import (
    HookedBackbone, run_yolo_detection_and_features, fuse_features,
    run_tracker_single_threshold, setup_trackeval_dirs, evaluate_hota,
    LAYER_ORDER, LAYER_CHANNELS_V8M,
)

sys.path.insert(0, str(Path(__file__).resolve().parents[3]))
from litepp.models.feature_pyramid import FeatureFusionModule

DANCETRACK_SEQUENCES = [
    "dancetrack0004", "dancetrack0014", "dancetrack0019", "dancetrack0035",
    "dancetrack0047", "dancetrack0063", "dancetrack0073", "dancetrack0077",
    "dancetrack0081", "dancetrack0090", "dancetrack0097",
]


def genuine_impostor_similarity(by_frame, fused_by_frame, gt_path, n_identities=6, seed=0):
    """Real genuine (same real GT identity) vs impostor (different identity)
    cosine similarity matrix from real fused embeddings, matched to GT boxes
    by nearest-IoU (detections are YOLOv8m boxes, not GT boxes directly)."""
    rng = np.random.RandomState(seed)
    gt_by_frame = {}
    for line in Path(gt_path).read_text(encoding="utf-8").splitlines():
        p = line.split(",")
        frame, tid = int(p[0]), int(p[1])
        x, y, w, h = map(float, p[2:6])
        gt_by_frame.setdefault(frame, []).append((tid, [x, y, x + w, y + h]))

    def iou(a, b):
        x1, y1 = max(a[0], b[0]), max(a[1], b[1])
        x2, y2 = min(a[2], b[2]), min(a[3], b[3])
        inter = max(0, x2 - x1) * max(0, y2 - y1)
        area_a = (a[2] - a[0]) * (a[3] - a[1])
        area_b = (b[2] - b[0]) * (b[3] - b[1])
        union = area_a + area_b - inter
        return inter / union if union > 0 else 0.0

    id_embeddings = {}
    for frame, dets in by_frame.items():
        if frame not in gt_by_frame or frame not in fused_by_frame:
            continue
        embs = fused_by_frame[frame]
        for i, rec in enumerate(dets):
            best_tid, best_iou = None, 0.3
            for tid, gt_box in gt_by_frame[frame]:
                v = iou(rec["bbox"], gt_box)
                if v > best_iou:
                    best_iou, best_tid = v, tid
            if best_tid is not None:
                id_embeddings.setdefault(best_tid, []).append(embs[i])

    ids = [tid for tid, v in id_embeddings.items() if len(v) >= 3]
    if len(ids) < n_identities:
        n_identities = len(ids)
    chosen = rng.choice(ids, size=n_identities, replace=False) if ids else []

    # Normalize every individual instance embedding (not a per-identity
    # centroid) so the diagonal is a real same-identity, different-instance
    # pairwise similarity rather than a vector's trivial self-similarity.
    inst_embs = {
        tid: [e / (np.linalg.norm(e) + 1e-8) for e in id_embeddings[tid]]
        for tid in chosen
    }
    sim = np.zeros((n_identities, n_identities))
    for i, ti in enumerate(chosen):
        for j, tj in enumerate(chosen):
            if i == j:
                vecs = inst_embs[ti]
                pair_sims = [float(np.dot(vecs[a], vecs[b]))
                             for a in range(len(vecs)) for b in range(len(vecs)) if a != b]
                sim[i, j] = float(np.mean(pair_sims)) if pair_sims else 1.0
            else:
                pair_sims = [float(np.dot(a, b)) for a in inst_embs[ti] for b in inst_embs[tj]]
                sim[i, j] = float(np.mean(pair_sims))
    return sim, list(chosen)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dancetrack_root", default="~/msfp/dancetrack_val")
    ap.add_argument("--mot17_root", default="/nas/Dataset/MOT/MOT17/train")
    ap.add_argument("--checkpoint", default="~/msfp/checkpoints/fusion_attention.pt")
    ap.add_argument("--atl_checkpoint", default="~/msfp/checkpoints/atl_paper_faithful.pt")
    ap.add_argument("--oracle_json", default="~/msfp/checkpoints/oracle_thresholds.json")
    ap.add_argument("--cache_det_dir", default="~/msfp/cache_det")
    ap.add_argument("--workdir", default="~/msfp/trackeval_dancetrack")
    ap.add_argument("--out", default="~/msfp/checkpoints/dancetrack_failure_analysis.json")
    ap.add_argument("--fixed_tau", type=float, default=0.5)
    args = ap.parse_args()

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    dt_root = Path(args.dancetrack_root).expanduser()
    workdir = Path(args.workdir).expanduser()
    workdir.mkdir(parents=True, exist_ok=True)

    sequences = [s for s in DANCETRACK_SEQUENCES if (dt_root / s / "img1").is_dir()]
    print(f"Found {len(sequences)} real DanceTrack-val sequences: {sequences}")

    ckpt = torch.load(Path(args.checkpoint).expanduser(), map_location=device, weights_only=False)
    layer_channels = [LAYER_CHANNELS_V8M[n] for n in LAYER_ORDER]
    fusion = FeatureFusionModule(layer_channels=layer_channels, output_dim=128,
                                  fusion_type="attention").to(device)
    fusion.load_state_dict(ckpt["state_dict"])
    fusion.eval()

    atl_ckpt = torch.load(Path(args.atl_checkpoint).expanduser(), map_location=device, weights_only=False)
    atl = ATLPaperFaithful(input_channels=576, hidden_dim=atl_ckpt["hidden_dim"]).to(device)
    atl.load_state_dict(atl_ckpt["state_dict"])
    atl.eval()

    backbone = HookedBackbone(device)

    # ---- Real detection + feature extraction on all DanceTrack-val sequences ----
    seq_info, by_frame_cache, fused_cache, scene_feat_cache = {}, {}, {}, {}
    all_det_scores = []
    t0 = time.time()
    for seq in sequences:
        print(f"[{seq}] real YOLOv8m detection + feature extraction...")
        by_frame, n_frames, scene_feats = run_yolo_detection_and_features(dt_root / seq, backbone, device)
        seq_info[seq] = n_frames
        fused_by_frame = {}
        for frame, recs in by_frame.items():
            fused_by_frame[frame] = fuse_features(recs, fusion, device)
            all_det_scores.extend([r["det_conf"] for r in recs])
        by_frame_cache[seq] = by_frame
        fused_cache[seq] = fused_by_frame
        scene_feat_cache[seq] = scene_feats
        print(f"  {n_frames} frames, {sum(len(v) for v in by_frame.values())} real detections")
    t_extract = time.time() - t0

    # ---- (a) Real genuine/impostor similarity on DanceTrack ----
    print("\n(a) Real genuine/impostor ReID similarity (DanceTrack, zero-shot MSFP head)...")
    seq_for_sim = sequences[0]
    sim_dt, ids_dt = genuine_impostor_similarity(
        by_frame_cache[seq_for_sim], fused_cache[seq_for_sim],
        dt_root / seq_for_sim / "gt" / "gt.txt", n_identities=6)
    genuine_dt = float(np.mean([sim_dt[i, i] for i in range(len(ids_dt))]))
    impostor_dt = float(np.mean([sim_dt[i, j] for i in range(len(ids_dt)) for j in range(len(ids_dt)) if i != j]))
    print(f"  DanceTrack ({seq_for_sim}): genuine={genuine_dt:.3f}, impostor={impostor_dt:.3f}, "
          f"gap={genuine_dt - impostor_dt:.3f}")

    # Real MOT17 comparison, reusing already-cached real GT-box features from extract_cached_features.py
    cache_dir = Path(args.cache_det_dir).expanduser()
    mot17_seq = "MOT17-02-FRCNN"
    mot17_by_frame_records = torch.load(cache_dir / f"{mot17_seq}.pt", weights_only=False)
    mot17_by_frame = {}
    for r in mot17_by_frame_records:
        mot17_by_frame.setdefault(r["frame"], []).append(r)
    mot17_fused_by_frame = {f: fuse_features(recs, fusion, device) for f, recs in mot17_by_frame.items()}
    sim_mot, ids_mot = genuine_impostor_similarity(
        mot17_by_frame, mot17_fused_by_frame,
        Path(args.mot17_root) / mot17_seq / "gt" / "gt.txt", n_identities=6)
    genuine_mot = float(np.mean([sim_mot[i, i] for i in range(len(ids_mot))]))
    impostor_mot = float(np.mean([sim_mot[i, j] for i in range(len(ids_mot)) for j in range(len(ids_mot)) if i != j]))
    print(f"  MOT17 ({mot17_seq}): genuine={genuine_mot:.3f}, impostor={impostor_mot:.3f}, "
          f"gap={genuine_mot - impostor_mot:.3f}")

    # ---- (b) Real DetA/AssA across 4 tracker configurations ----
    print("\n(b) Real tracker configuration comparison on DanceTrack-val...")
    zero_feats = {seq: {f: np.zeros((len(recs), 128), dtype=np.float32) for f, recs in by_frame_cache[seq].items()}
                  for seq in sequences}
    layer9_feats = {}
    for seq in sequences:
        layer9_feats[seq] = {}
        for frame, recs in by_frame_cache[seq].items():
            if not recs:
                layer9_feats[seq][frame] = np.zeros((0, 576), dtype=np.float32)
                continue
            raw = torch.stack([r["layer9"] for r in recs]).numpy()
            norm = raw / (np.linalg.norm(raw, axis=1, keepdims=True) + 1e-8)
            layer9_feats[seq][frame] = norm

    tracker_name = "MSFP-Track-dt"
    gt_folder, trackers_folder = setup_trackeval_dirs(workdir, dt_root, sequences, tracker_name)

    def eval_config(fused_by_seq, tau_by_seq, appearance_weight, label):
        for seq in sequences:
            tracker = ByteTrackStyleTracker(tau_h=tau_by_seq[seq], tau_l=tau_by_seq[seq],
                                             max_age=30, min_hits=1, appearance_weight=appearance_weight,
                                             high_stage_cost_thresh=0.7 if appearance_weight > 0 else 1.0)
            lines = []
            for frame in range(1, seq_info[seq] + 1):
                recs = by_frame_cache[seq].get(frame, [])
                if recs:
                    boxes = np.array([r["bbox"] for r in recs], dtype=np.float32)
                    scores = np.array([r["det_conf"] for r in recs], dtype=np.float32)
                    feats = fused_by_seq[seq].get(frame, np.zeros((len(recs), 128), dtype=np.float32))
                else:
                    boxes = np.zeros((0, 4), dtype=np.float32)
                    scores = np.zeros((0,), dtype=np.float32)
                    feats = np.zeros((0, feats_dim), dtype=np.float32) if False else np.zeros((0, 128), dtype=np.float32)
                results = tracker.update(boxes, scores, feats)
                for tid, x1, y1, x2, y2 in results:
                    w, h = x2 - x1, y2 - y1
                    lines.append(f"{frame},{tid},{x1:.2f},{y1:.2f},{w:.2f},{h:.2f},1,-1,-1,-1")
            out_file = trackers_folder / tracker_name / "data" / f"{seq}.txt"
            out_file.parent.mkdir(parents=True, exist_ok=True)
            out_file.write_text("\n".join(lines), encoding="utf-8")
        hota = evaluate_hota(gt_folder, trackers_folder, sequences, tracker_name, seq_info)
        mean_hota = float(np.mean([hota[s]['HOTA'] for s in sequences]))
        mean_deta = float(np.mean([hota[s]['DetA'] for s in sequences]))
        mean_assa = float(np.mean([hota[s]['AssA'] for s in sequences]))
        print(f"  [{label}] mean HOTA={mean_hota:.2f}  DetA={mean_deta:.2f}  AssA={mean_assa:.2f}")
        return {"per_seq": hota, "mean_HOTA": mean_hota, "mean_DetA": mean_deta, "mean_AssA": mean_assa}

    fixed_tau_by_seq = {seq: args.fixed_tau for seq in sequences}
    results_motion = eval_config(zero_feats, fixed_tau_by_seq, 0.0, "ByteTrack (motion-only)")
    results_lite = eval_config(layer9_feats, fixed_tau_by_seq, 0.5, "LITE (1-layer, layer9)")
    results_msfp = eval_config(fused_cache, fixed_tau_by_seq, 0.5, "MSFP (attention fusion)")

    print("\nReal zero-shot ATL threshold prediction per DanceTrack sequence...")
    atl_tau_by_seq = {}
    with torch.no_grad():
        for seq in sequences:
            feats = scene_feat_cache[seq]
            mean_feat = feats.mean(dim=0, keepdim=True).to(device)
            atl_tau_by_seq[seq] = float(atl.forward_from_gap(mean_feat).item())
            print(f"  {seq}: ATL tau={atl_tau_by_seq[seq]:.3f}")
    results_msfp_atl = eval_config(fused_cache, atl_tau_by_seq, 0.5, "MSFP-Track (+zero-shot ATL)")

    # ---- (c) Score distribution + threshold comparison ----
    mot17_cache_scores = []
    for f in ["MOT17-02-FRCNN", "MOT17-04-FRCNN", "MOT17-09-FRCNN"]:
        recs = torch.load(cache_dir / f"{f}.pt", weights_only=False)
        mot17_cache_scores.extend([r["det_conf"] for r in recs])

    oracle_data = json.load(open(Path(args.oracle_json).expanduser(), encoding="utf-8"))
    mot17_oracle_taus = [v["tau_star"] for v in oracle_data["oracle_per_sequence"].values()]

    result = {
        "sequences": sequences,
        "similarity": {
            "dancetrack_seq": seq_for_sim, "mot17_seq": mot17_seq,
            "genuine_dancetrack": genuine_dt, "impostor_dancetrack": impostor_dt,
            "genuine_mot17": genuine_mot, "impostor_mot17": impostor_mot,
            "sim_matrix_dancetrack": sim_dt.tolist(), "sim_matrix_mot17": sim_mot.tolist(),
        },
        "tracker_comparison": {
            "ByteTrack_motion_only": results_motion,
            "LITE_1layer": results_lite,
            "MSFP_attention": results_msfp,
            "MSFP_Track_ATL": results_msfp_atl,
        },
        "atl_tau_dancetrack_per_seq": atl_tau_by_seq,
        "atl_tau_dancetrack_mean": float(np.mean(list(atl_tau_by_seq.values()))),
        "mot17_oracle_tau_mean": float(np.mean(mot17_oracle_taus)),
        "det_score_sample_dancetrack": list(np.random.choice(all_det_scores, size=min(3000, len(all_det_scores)), replace=False)),
        "det_score_sample_mot17": list(np.random.choice(mot17_cache_scores, size=min(3000, len(mot17_cache_scores)), replace=False)),
        "timing": {"feature_extraction_seconds": t_extract,
                   "device": torch.cuda.get_device_name(0) if device.type == "cuda" else "cpu"},
    }
    out_path = Path(args.out).expanduser()
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(result, f, indent=2)
    print(f"\nSaved -> {out_path}")


if __name__ == "__main__":
    main()
